### ISSUE TITLE
osx error, 'libintl.h' file not found

### ISSUE THREAD

**Issue by nickgal** [nerves-project/nerves-toolchain#1]
`brew install gettext` seemed to fix it. 

edit: I'm using 10.11 el capitain.

**Comment by fhunleth** [comment]
Thanks. Good catch. I added it to the readme.

BTW, this repository is majorly under development as we try to get crosscompilers working outside of the Buildroot environment so that we can do local (non-VM) builds on OSX. When Justin and I get a little farther, we probably could use some help, but right now, we're hacking things together just to try out concepts. I expect that we'll reorganize this repo to make a lot more sense once the dust settles. Stay tuned since it will be great to get feedback when we're farther along.
